@extends('layouts.app')
@section('title', 'Analytics · Legatus')
@section('body')
<div class="dash-shell">
    @include('partials.workspace-navigation', ['active' => 'analytics'])
    <main class="main"><div class="topline"><div><span class="eyebrow">Evidence, not guesswork</span><h1>AI performance</h1><p style="color:var(--muted);margin:6px 0">Customer activity excludes evaluation traffic. Seeded traces stay visible and are explicitly labeled.</p></div><span class="tag"><span class="dot"></span> Observability active</span></div>
        <div class="grid"><div class="stat"><small>Conversations</small><b>{{ number_format($metrics['conversations']) }}</b><span class="channel">Customer channels · eval excluded</span></div><div class="stat"><small>Automation rate</small><b>{{ $metrics['automation_rate'] }}%</b><span class="up">Never required human handoff</span></div><div class="stat"><small>Qualified leads</small><b>{{ number_format($metrics['qualified_leads']) }}</b><span class="up">Qualified or won · consent-backed</span></div><div class="stat"><small>Value influenced</small><b>{{ number_format($metrics['revenue_influenced'],2) }} ₾</b><span class="channel">Offers & reservations</span></div></div>
        <div class="content-grid"><section class="panel"><div style="display:flex;justify-content:space-between;align-items:center"><div><span class="eyebrow">Agent traces</span><h3 style="margin-top:6px">Recent model runs</h3></div><span class="tag">Avg {{ number_format($metrics['avg_latency']) }} ms</span></div>
            @forelse($runs as $run)<div class="conversation"><span class="avatar" style="width:36px;height:36px;border-radius:11px">{{ $run->status === 'completed' ? '✓' : ($run->status === 'failed' ? '!' : '↻') }}</span><div class="copy"><b>{{ $run->model }}</b> @if(str_starts_with($run->response_id ?? '', 'demo-trace-'))<span class="tag" style="padding:3px 6px">Simulated demo data</span>@endif<p>{{ collect($run->tools_used ?? [])->map(fn($tool)=>is_array($tool)?($tool['name']??'tool'):$tool)->join(' → ') ?: 'No tool calls' }}</p></div><div style="text-align:right"><span class="pill">{{ $run->status }}</span><div class="channel">{{ number_format(($run->input_tokens ?? 0)+($run->output_tokens ?? 0)) }} tokens · {{ number_format($run->latency_ms ?? 0) }} ms</div></div></div>@empty<p style="color:var(--muted)">Send a demo message to create the first trace.</p>@endforelse
        </section><aside><section class="agent-card"><span class="eyebrow" style="color:#bcd0c9">Quality gate</span>@if($eval)<h2 style="font-size:40px;margin:12px 0">{{ $eval->passed }}/{{ $eval->passed + $eval->failed }}</h2><p>Latest {{ $eval->mode }} evaluation · {{ $eval->created_at->diffForHumans() }}</p><div class="progress"><i style="width:{{ ($eval->passed / max(1,$eval->passed+$eval->failed))*100 }}%"></i></div>@else<h3 style="margin-top:12px">No evaluation yet</h3><p>Run <code>php artisan legatus:eval</code> for a deterministic baseline.</p>@endif</section>
            <section class="panel" style="margin-top:18px"><h3>Usage & quality</h3>@if($metrics['simulated_runs'])<p class="channel">Totals below exclude eval traffic and include {{ $metrics['simulated_runs'] }} clearly labeled simulated demo traces.</p>@endif<div class="conversation"><div class="copy"><b>{{ number_format($metrics['input_tokens']) }}</b><p>Input tokens</p></div></div><div class="conversation"><div class="copy"><b>{{ number_format($metrics['output_tokens']) }}</b><p>Output tokens</p></div></div><div class="conversation"><div class="copy"><b>{{ number_format($metrics['recommendations']) }}</b><p>Recommendation journeys</p></div></div><div class="conversation"><div class="copy"><b>{{ $metrics['helpfulness_rate']===null?'—':$metrics['helpfulness_rate'].'%' }}</b><p>Helpful response rating</p></div></div><div class="conversation"><div class="copy"><b>{{ number_format($metrics['handoffs']) }}</b><p>Human handoffs</p></div></div></section>
        </aside></div>
    </main>
</div>
@endsection
